package com.bojanvilic.film.theme

import androidx.compose.ui.graphics.Color

val light_theme_primary = Color(0xff157d76)
val light_theme_secondary = Color(0xff13baae)
val light_theme_tertiary = Color(0xFF800000)
val light_theme_error = Color(0xFFFFB4AB)
val light_theme_errorContainer = Color(0xFF93000A)
val light_theme_onError = Color(0xFF690005)
val light_theme_onErrorContainer = Color(0xFFFFDAD6)
val light_theme_background = Color(0xFFeeeeee)
val light_theme_onBackground = Color(0xFFeeeeee)
val light_theme_surfaceTint = Color(0xFFeeeeee)
val light_theme_surfaceVariant = Color(0xFFF1EAEA)
val light_theme_onSurfaceVariant = Color(0xFF1b1b1b)

val dark_theme_primary = Color(0xFFBE0001)
val dark_theme_secondary = Color(0xFF800000)
val dark_theme_tertiary = Color(0xFFFFB3B4)
val dark_theme_error = Color(0xFFFFB4AB)
val dark_theme_errorContainer = Color(0xFF93000A)
val dark_theme_onError = Color(0xFF690005)
val dark_theme_onErrorContainer = Color(0xFFFFDAD6)
val dark_theme_background = Color(0xFF1b1b1b)
val dark_theme_onBackground = Color(0xFF1b1b1b)
val dark_theme_surfaceTint = Color(0xFF1b1b1b)
val dark_theme_surfaceVariant = Color(0xFF303030)
val dark_theme_onSurfaceVariant = Color(0xFFefefef)
val dark_theme_inverseSurface = Color(0xFF1b1b1b)
val dark_theme_inverseOnSurface = Color(0xFFefefef)